import crypto from 'node:crypto';
import os from 'node:os';
import { globalCliRuntime, normalizeCliConfig } from './cli/cliRuntimeManager.js';
import { isCliProvider, CLI_IDS, type CliProviderId } from '../shared/cli.js';
import fs from 'fs';
import { isQuickPromptConversation } from '../shared/conversationScope.js';
import { createUpdateChecker } from './updates.js';
import path from 'path';
import { pathToFileURL, fileURLToPath } from 'url';
import { app, ipcMain, BrowserWindow, globalShortcut, Menu, MenuItem, dialog, protocol, net, shell } from 'electron';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import { globalWindowManager } from './window.js';
import { TrayManager } from './tray.js';
import { globalMcpServer } from './mcp/server.js';
import { globalSessionManager } from './webviews/sessionManager.js';
import { globalBlindingEngine } from './security/dataBlinding.js';
import { globalAssetManager } from './storage/assetManager.js';
import { SessionProfileManager } from './security/antiDetection.js';
import { CdpCompatibilityManager } from './security/cdpStealth.js';
import { DynamicRouter } from './mcp/router.js';
import { ModelRegistryManager } from './registry/modelRegistry.js';
import { ModelScraperEngine } from './registry/modelScrapers.js';
import { globalRateLimiter } from './mcp/rateLimiter.js';
import { globalThreadManager } from './registry/threadManager.js';
import { ServiceManifestManager } from './registry/serviceManifest.js';
import { AccountRegistryManager } from './registry/accountRegistry.js';
import { ClientAuthManager } from './security/clientAuth.js';
import { LocalLlmClient } from './localllm/localLlmClient.js';
import { globalHealingManager } from './healing/healingManager.js';
import { globalRecipeManager } from './registry/recipeManager.js';
import {
  MODE_SCHEMA_VERSION,
  AgentHaltGuardConfig,
  doubleAgentConfig,
  HealingConfig,
  LocalLLMConfig,
  ModeRouteConfig,
  ProviderConfig,
  ProviderId,
  RecallConfig,
  RouteMode,
  TaskMode,
  TransgenticConfig,
  normalizeModeFlags,
  normalizeTaskMode,
} from '../shared/types.js';
import { getExtensionDownloadUrl } from '../shared/release.js';
import { ATTACHMENT_LIMITS, type AttachmentInput, type DesktopAttachmentSelection } from '../shared/attachments.js';

// Register custom protocol for local media streaming
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'transgentic-media',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
      bypassCSP: true,
    },
  },
]);

// Suppress dev-mode CSP warning generated by Vite HMR eval requirements
process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true';

// 1. Standard host-aligned Chromium runtime configuration
app.commandLine.appendSwitch('disable-blink-features', 'AutomationControlled');
app.commandLine.appendSwitch('disable-features', 'IsolateOrigins,site-per-process');
app.userAgentFallback = SessionProfileManager.getNormalizedUserAgent();

let trayManager: TrayManager | null = null;

function getConfigPath(): string {
  try {
    if (app && typeof app.getPath === 'function') {
      return path.join(app.getPath('userData'), 'transgentic_config.json');
    }
  } catch {}
  return path.join(process.cwd(), 'transgentic_config.json');
}

function getDefaultAssetsDir(): string {
  try {
    if (app && typeof app.getPath === 'function') {
      return path.join(app.getPath('documents'), 'Transgentic');
    }
  } catch {}
  const homeDir = process.env.HOME || process.env.USERPROFILE || process.cwd();
  return path.join(homeDir, 'Documents', 'Transgentic');
}

function loadPersistedConfig(): TransgenticConfig {
  const defaultAssetsDir = getDefaultAssetsDir();
  const defaults: TransgenticConfig = {
    modeSchemaVersion: MODE_SCHEMA_VERSION,
    cli: normalizeCliConfig(),
    serverAccess: { lanEnabled: false, advertisedAddress: '' },
    port: 58420,
    defaultMode: 'general',
    interMessageCooldownMs: 6000,
    textJitterMinMs: 3000,
    textJitterMaxMs: 8000,
    mediaJitterMinMs: 12000,
    mediaJitterMaxMs: 25000,
    autoFallbackEnabled: true,
    dataBlindingEnabled: true,
    assetsDir: defaultAssetsDir,
    balancedMode: true,
    doubleAgent: {
      enabled: false,
      includeLocalLlm: false,
      completionReviewEnabled: false,
      modes: {
        general: true,
        coding: true,
        image: true,
        video: true,
        music: true,
      },
    },
    routes: DynamicRouter.getRouteMatrix(),
    coding: {
      balancedMode: true,
      primaryProvider: 'claude',
      fallbackProviders: ['chatgpt', 'gemini', 'grok'],
    },
    recall: {
      enabled: true,
      strategy: 'single-pass',
      autoTriggerKeywords: true,
      completionEnabled: false,
      modes: {
        general: true,
        coding: true,
        image: true,
        video: true,
        music: true,
      },
    },
    agentHaltGuard: {
      general: true,
      coding: true,
      image: true,
      video: true,
      music: true,
    },
    localLLM: {
      enabled: false,
      preset: 'ollama',
      baseUrl: 'http://127.0.0.1:11434',
      selectedModel: '',
      temperature: 0.2,
      contextLength: 8192,
      completionCompact: false,
      attachmentKinds: [],
    },
    healing: {
      autoHealingEnabled: true,
      checkIntervalMinutes: 60,
      checkOnPageLoad: true,
      checkModelSelector: true,
    },
  };

  try {
    const configPath = getConfigPath();
    if (fs.existsSync(configPath)) {
      const raw = fs.readFileSync(configPath, 'utf-8');
      const parsed = JSON.parse(raw);
      const isLegacyModeSchema = parsed.modeSchemaVersion !== MODE_SCHEMA_VERSION;
      const legacyCompletion = parsed.completion && typeof parsed.completion === 'object' ? parsed.completion : undefined;
      const hadCompletionRecall = Object.prototype.hasOwnProperty.call(parsed.recall || {}, 'completionEnabled');
      const hadCompletionCompact = Object.prototype.hasOwnProperty.call(parsed.localLLM || {}, 'completionCompact');
      const hadCompletionReview = Object.prototype.hasOwnProperty.call(parsed.doubleAgent || {}, 'completionReviewEnabled');
      // Migrate old developer workspace path or relative ./assets to clean Documents/Transgentic
      if (!parsed.assetsDir || parsed.assetsDir === './assets' || parsed.assetsDir.includes('/Workspace/Apps/transgentic')) {
        parsed.assetsDir = defaultAssetsDir;
      }
      if (!parsed.coding) {
        parsed.coding = defaults.coding;
      } else if (parsed.coding.balancedMode === undefined) {
        parsed.coding.balancedMode = true;
      }
      if (!parsed.recall) {
        parsed.recall = defaults.recall;
      } else {
        parsed.recall.modes = normalizeModeFlags(parsed.recall.modes);
      }
      if (!parsed.agentHaltGuard) {
        parsed.agentHaltGuard = defaults.agentHaltGuard;
      } else if (typeof parsed.agentHaltGuard === 'boolean') {
        const val = parsed.agentHaltGuard;
        parsed.agentHaltGuard = {
          general: val,
          coding: val,
          image: val,
          video: val,
          music: val,
        };
      } else {
        parsed.agentHaltGuard = normalizeModeFlags(parsed.agentHaltGuard);
      }
      // Non-destructively preserve localLLM configuration (does not wipe endpoints/models on enabled: false)
      if (!parsed.localLLM) {
        parsed.localLLM = defaults.localLLM;
      } else {
        parsed.localLLM = {
          ...defaults.localLLM,
          ...parsed.localLLM,
        };
      }
      if (!parsed.healing) {
        parsed.healing = defaults.healing;
      } else {
        parsed.healing = {
          ...defaults.healing,
          ...parsed.healing,
        };
      }
      if (parsed.balancedMode === undefined) {
        parsed.balancedMode = parsed.coding?.balancedMode ?? true;
      }
      if (parsed.coding) {
        parsed.coding.balancedMode = parsed.balancedMode;
      }
      if (!parsed.doubleAgent) {
        parsed.doubleAgent = defaults.doubleAgent;
      } else {
        const legacyModes = parsed.doubleAgent.modes || {};
        parsed.doubleAgent = {
          ...defaults.doubleAgent,
          ...parsed.doubleAgent,
          modes: normalizeModeFlags(legacyModes),
        };
      }
      parsed.routes = parsed.routes
        ? DynamicRouter.migrateRouteMatrix(parsed.routes)
        : DynamicRouter.getRouteMatrix();
      parsed.serverAccess = { ...defaults.serverAccess, ...(parsed.serverAccess || {}) };
      // Preserve opt-ins created by the first completion-gateway release while
      // moving each setting to the feature that owns it.
      if (legacyCompletion) {
        if (!hadCompletionRecall) parsed.recall.completionEnabled = legacyCompletion.recall === true;
        if (!hadCompletionCompact) parsed.localLLM.completionCompact = legacyCompletion.compaction === true;
        if (!hadCompletionReview) parsed.doubleAgent.completionReviewEnabled = legacyCompletion.multiModelReview === true;
        delete parsed.completion;
      }
      // CLI configurations created before Provider/Agentic modes migrate to
      // Provider Mode. normalizeCliConfig also clears host permissions there.
      parsed.cli = normalizeCliConfig(parsed.cli);
      parsed.defaultMode = isLegacyModeSchema && parsed.defaultMode === 'audio'
        ? 'music'
        : normalizeTaskMode(parsed.defaultMode);
      parsed.modeSchemaVersion = MODE_SCHEMA_VERSION;
      return { ...defaults, ...parsed };
    }
  } catch {}
  return defaults;
}

function savePersistedConfig(cfg: TransgenticConfig): void {
  try {
    const configPath = getConfigPath();
    const dir = path.dirname(configPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(configPath, JSON.stringify({ ...cfg, modeSchemaVersion: MODE_SCHEMA_VERSION }, null, 2), 'utf-8');
  } catch {}
}

// Helpers for local media asset handling and streaming
function sanitizeLocalPath(rawPath: string): string {
  if (!rawPath || typeof rawPath !== 'string') return '';
  let clean = rawPath.trim().replace(/^['"]|['"]$/g, '');
  if (clean.startsWith('file://')) {
    clean = clean.replace(/^file:\/\//i, '');
    if (process.platform === 'win32' && /^\/[a-zA-Z]:/.test(clean)) {
      clean = clean.slice(1);
    }
  }
  try {
    clean = decodeURIComponent(clean);
  } catch {}
  return path.normalize(clean);
}

function getMediaMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  switch (ext) {
    case '.jpg':
    case '.jpeg':
      return 'image/jpeg';
    case '.png':
      return 'image/png';
    case '.webp':
      return 'image/webp';
    case '.gif':
      return 'image/gif';
    case '.svg':
      return 'image/svg+xml';
    case '.bmp':
      return 'image/bmp';
    case '.mp4':
      return 'video/mp4';
    case '.webm':
      return 'video/webm';
    case '.mov':
      return 'video/quicktime';
    case '.mkv':
      return 'video/x-matroska';
    case '.mp3':
      return 'audio/mpeg';
    case '.wav':
      return 'audio/wav';
    case '.ogg':
      return 'audio/ogg';
    case '.m4a':
      return 'audio/mp4';
    case '.aac':
      return 'audio/aac';
    case '.flac':
      return 'audio/flac';
    default:
      return 'application/octet-stream';
  }
}

let currentConfig: TransgenticConfig = loadPersistedConfig();

async function bootstrap() {
  // Prevent multiple instances
  const gotTheLock = app.requestSingleInstanceLock();
  if (!gotTheLock) {
    app.quit();
    return;
  }

  app.on('second-instance', () => {
    globalWindowManager.show();
  });

  await app.whenReady();

  // Handle local media streaming via custom protocol
  protocol.handle('transgentic-media', async (request) => {
    try {
      let raw = request.url.replace(/^transgentic-media:\/\/?/i, '');
      if (process.platform !== 'win32' && !raw.startsWith('/')) {
        raw = '/' + raw;
      }
      if (process.platform === 'win32' && /^\/[a-zA-Z]:/.test(raw)) {
        raw = raw.slice(1);
      }
      const filePath = sanitizeLocalPath(raw);

      if (!filePath || !fs.existsSync(filePath)) {
        return new Response('File Not Found', { status: 404 });
      }

      const stat = await fs.promises.stat(filePath);
      const fileSize = stat.size;
      const mime = getMediaMimeType(filePath);

      // Support Range requests (essential for smooth video/audio playback and scrubbing)
      const rangeHeader = request.headers.get('range');
      if (rangeHeader && rangeHeader.startsWith('bytes=')) {
        const parts = rangeHeader.replace(/bytes=/, '').split('-');
        const start = parseInt(parts[0], 10) || 0;
        const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
        if (start < fileSize) {
          const clampedEnd = Math.min(end, fileSize - 1);
          const chunkLength = clampedEnd - start + 1;
          const fd = await fs.promises.open(filePath, 'r');
          const buffer = Buffer.alloc(chunkLength);
          await fd.read(buffer, 0, chunkLength, start);
          await fd.close();
          return new Response(buffer, {
            status: 206,
            headers: {
              'Content-Range': `bytes ${start}-${clampedEnd}/${fileSize}`,
              'Accept-Ranges': 'bytes',
              'Content-Length': String(chunkLength),
              'Content-Type': mime,
              'Cache-Control': 'no-cache',
            },
          });
        }
      }

      const buf = await fs.promises.readFile(filePath);
      return new Response(buf, {
        status: 200,
        headers: {
          'Accept-Ranges': 'bytes',
          'Content-Length': String(buf.length),
          'Content-Type': mime,
          'Cache-Control': 'no-cache',
        },
      });
    } catch (err: any) {
      return new Response('Not Found', { status: 404 });
    }
  });

  // Load config & apply storage directory & rate limits
  currentConfig = loadPersistedConfig();
  if (currentConfig.assetsDir) {
    globalAssetManager.setAssetsDirectory(currentConfig.assetsDir);
    globalRecipeManager.setStorageDirectory(currentConfig.assetsDir);
  }
  ModelRegistryManager.loadPersistedRegistry();
  ServiceManifestManager.getManifest();
  AccountRegistryManager.initialize();
  globalRateLimiter.updateConfig(currentConfig);
  globalHealingManager.setTransgenticConfig(currentConfig);
  globalMcpServer.updateConfig(currentConfig);
  if (currentConfig.localLLM) {
    DynamicRouter.setLocalLlmConfig(currentConfig.localLLM);
  }

function getStealthPreloadPath(): string | undefined {
  try {
    const candidates = [
      path.join(__dirname, 'preload/stealthPreload.cjs'),
      path.join(__dirname, '../preload/stealthPreload.cjs'),
      path.join(app.getAppPath(), 'dist-electron/main/preload/stealthPreload.cjs'),
      path.join(process.cwd(), 'dist-electron/main/preload/stealthPreload.cjs'),
    ];
    for (const p of candidates) {
      if (fs.existsSync(p)) return p;
    }
  } catch {}
  return undefined;
}

  // 1. Initialize persistent sessions and anti-detection
  globalRecipeManager.initializeAllCustomRecipes();
  globalSessionManager.initializeSessions();

  // 2. Setup WebContents Listener for guest Webviews, main window, and OAuth popups
  app.on('web-contents-created', (_, contents) => {
    const normalizedUA = SessionProfileManager.getNormalizedUserAgent();
    contents.setUserAgent(normalizedUA);
    contents.setMaxListeners(50);

    // Ensure any partition session is configured with anti-detection headers
    const guestPartition = (contents.session as any)?.partition || '';
    if (guestPartition) {
      globalSessionManager.configureSession(guestPartition);
    }

    // Enable Right-Click -> Inspect Element in development mode
    const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged || !!process.env.VITE_DEV_SERVER_URL;
    if (isDev) {
      contents.on('context-menu', (_, params) => {
        const menu = new Menu();
        menu.append(
          new MenuItem({
            label: 'Inspect Element',
            click: () => {
              contents.inspectElement(params.x, params.y);
            },
          })
        );
        menu.popup();
      });
    }

    // Ensure popups (e.g. Google OAuth / ThaID / NextAuth) open cleanly with full partition session and stealth preload
    const session = contents.session;
    const partition = (session as any).partition || '';

    contents.setWindowOpenHandler((details) => {
      const targetUrl = details.url.toLowerCase();
      const stealthPreload = getStealthPreloadPath();

      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          autoHideMenuBar: true,
          alwaysOnTop: true,
          webPreferences: {
            partition: partition || undefined,
            preload: stealthPreload,
            nodeIntegration: false,
            contextIsolation: true,
          },
        },
      };
    });

    contents.on('did-create-window', (childWindow) => {
      childWindow.webContents.setUserAgent(normalizedUA);
      childWindow.webContents.on('dom-ready', () => {
        childWindow.webContents.executeJavaScript(SessionProfileManager.getPreloadCompatibilityScript(), true).catch(() => {});
      });
    });

    // Apply browser environment alignment to guest session
    CdpCompatibilityManager.attachCompatibility(contents);

    // Listen for URL changes, in-page navigation, and page load to auto-update auth state
    const handleNavigation = (url: string) => {
      if (!url) return;
      const matched = globalSessionManager.getProviderFromUrl(url);
      if (matched) {
        globalSessionManager.registerWebContents(matched, contents);
        globalSessionManager.refreshProviderStatus(matched);
      }
    };

    contents.on('did-navigate', (_, url) => handleNavigation(url));
    contents.on('did-navigate-in-page', (_, url) => handleNavigation(url));
    contents.on('did-finish-load', () => {
      const u = contents.getURL();
      handleNavigation(u);
      const matchedP = globalSessionManager.getProviderFromUrl(u);
      if (matchedP) {
        globalHealingManager.handleWebContentsLoaded(matchedP, contents);
      }
    });
    contents.on('dom-ready', () => handleNavigation(contents.getURL()));
  });

  // 3. Register IPC handlers early before window and renderer connection
  setupIpcHandlers();

  // 4. Start Local MCP Server on configured port
  const actualPort = await globalMcpServer.restart(currentConfig.port);
  currentConfig.port = actualPort;
  savePersistedConfig(currentConfig);

  // 5. Create Main Squircle Window
  const mainWindow = globalWindowManager.createMainWindow();

  // Verify enabled native services in the background. Each connection check is
  // answer-only and runs without a registered workspace or project permissions.
  const enabledCliProviders = CLI_IDS.filter(id => ServiceManifestManager.isServiceEnabled(id));
  if (enabledCliProviders.length > 0) {
    void globalCliRuntime.testEnabledConnections(enabledCliProviders);
  }

  globalHealingManager.onUpdate((reports) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('healing-reports-updated', reports);
    }
  });

  // 6. Create System Tray safely
  try {
    trayManager = new TrayManager(() => {
      globalWindowManager.show();
    });
    trayManager.createTray();
  } catch (err: any) {
    console.warn('[Transgentic] Tray creation notice:', err.message);
  }

  // 7. Register Global Shortcut (Option+Space or Alt+Space) for Spotlight summon
  try {
    globalShortcut.register('Option+Space', () => {
      const win = globalWindowManager.getMainWindow();
      if (win?.isVisible() && win?.isFocused()) {
        win.hide();
      } else {
        globalWindowManager.show();
      }
    });
  } catch (err: any) {
    console.warn('[Transgentic] Global shortcut register note:', err.message);
  }

  // 8. Forward real-time events to UI
  globalMcpServer.onCoreStatus((status) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('core-status-updated', status);
    }
  });

  globalSessionManager.onStatusUpdate((statuses) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('provider-status-updated', { ...statuses, ...globalCliRuntime.getStatuses() });
    }
  });

  globalMcpServer.onLog((log) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('request-log-added', log);
    }
  });

  ModelRegistryManager.onRegistryUpdate((registry) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('models-updated', registry);
    }
  });

  globalThreadManager.onSessionsUpdate((sessions) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('threads-updated', sessions);
    }
  });

  ServiceManifestManager.onManifestUpdate((manifest) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('services-manifest-updated', manifest);
    }
  });

  AccountRegistryManager.onAccountsUpdated((accounts) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('accounts-updated', accounts);
    }
  });

  globalBlindingEngine.onSecretsUpdate((secrets) => {
    if (!mainWindow.isDestroyed()) {
      mainWindow.webContents.send('secrets-updated', secrets);
      mainWindow.webContents.send('core-status-updated', globalMcpServer.getCoreStatus());
    }
  });
}

function setupIpcHandlers() {
  const cliState = () => globalCliRuntime.getState();
  const persistCli = (config: import('../shared/cli.js').CliConfig) => {
    currentConfig = { ...currentConfig, cli: normalizeCliConfig(config) };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    globalWindowManager.getMainWindow()?.webContents.send('config-updated', currentConfig);
    return cliState();
  };
  const handleCli = (name: string, fn: (...args: any[]) => any) => ipcMain.handle(name, (event, ...args) => {
    if (event.sender !== globalWindowManager.getMainWindow()?.webContents || event.senderFrame !== event.sender.mainFrame) throw new Error('CLI settings are available only in the desktop window.');
    return fn(...args);
  });
  handleCli('cli:state', cliState);
  handleCli('cli:configure', (id, updates) => persistCli(globalCliRuntime.validateServiceUpdates(id, updates).config));
  handleCli('cli:probe', async id => { if (!isCliProvider(id)) throw new Error('Unknown CLI service.'); await globalCliRuntime.probe(id); return cliState(); });
  handleCli('cli:models', async (id, force) => {
    if (!isCliProvider(id) || (force !== undefined && typeof force !== 'boolean')) throw new Error('Unknown CLI service.');
    return globalCliRuntime.discoverModels(id, force === true);
  });
  handleCli('cli:test', async id => {
    if (!isCliProvider(id)) throw new Error('Unknown CLI service.');
    return globalCliRuntime.testConnection(id);
  });
  handleCli('cli:select-executable', async id => {
    if (!isCliProvider(id)) throw new Error('Unknown CLI service.');
    const selected = await dialog.showOpenDialog(globalWindowManager.getMainWindow()!, { title: 'Select CLI executable', properties: ['openFile'] });
    if (!selected.canceled && selected.filePaths[0]) persistCli(globalCliRuntime.validateServiceUpdates(id, { executablePath: selected.filePaths[0] }).config);
    await globalCliRuntime.probe(id); return cliState();
  });
  handleCli('cli:add-workspace', async () => {
    const selected = await dialog.showOpenDialog(globalWindowManager.getMainWindow()!, { title: 'Register CLI workspace', properties: ['openDirectory'] });
    if (selected.canceled || !selected.filePaths[0]) return cliState();
    const real = fs.realpathSync(selected.filePaths[0]);
    const config = cliState().config;
    if (!config.workspaces.some(w => w.path === real)) config.workspaces.push({ id: crypto.randomUUID(), name: path.basename(real), path: real, allowMcp: false, grants: {} });
    return persistCli(config);
  });
  handleCli('cli:update-workspace', (id, updates) => {
    const config = cliState().config; const workspace = config.workspaces.find(w => w.id === id);
    if (!workspace || !updates || typeof updates.allowMcp !== 'boolean' || !updates.grants || Object.keys(updates).some(k => !['allowMcp', 'grants'].includes(k))) throw new Error('Invalid workspace permissions.');
    workspace.grants = updates.grants; workspace.allowMcp = updates.allowMcp;
    return persistCli(config);
  });
  handleCli('cli:remove-workspace', id => { const config = cliState().config; config.workspaces = config.workspaces.filter(w => w.id !== id); return persistCli(config); });
  globalCliRuntime.onUpdate(() => globalWindowManager.getMainWindow()?.webContents.send('provider-status-updated', { ...globalSessionManager.getAllStatuses(), ...globalCliRuntime.getStatuses() }));

  const checkForUpdate = createUpdateChecker();
  ipcMain.handle('app:check-for-update', () => checkForUpdate(app.getVersion()));
  ipcMain.handle('get-core-status', () => globalMcpServer.getCoreStatus());
  ipcMain.handle('get-provider-statuses', () => ({ ...globalSessionManager.getAllStatuses(), ...globalCliRuntime.getStatuses() }));
  ipcMain.handle('get-blinded-secrets', () => globalBlindingEngine.getVaultEntries());
  ipcMain.handle('clear-vault-secrets', () => globalBlindingEngine.clearVault());
  ipcMain.handle('mem:wipe-all', () => {
    globalBlindingEngine.clearVault();
    return true;
  });
  ipcMain.handle('storage:clear-browser-storage', async () => {
    return await globalSessionManager.clearAllBrowserStorage();
  });
  ipcMain.handle('storage:purge-all-data', async () => {
    const browserResult = await globalSessionManager.clearAllBrowserStorage();
    globalCliRuntime.dispose(); globalCliRuntime.clearSessions();
    globalBlindingEngine.clearVault();
    globalThreadManager.clearAll();
    globalMcpServer.clearRequestLogs();
    globalRateLimiter.resetAll();
    return { success: true, ...browserResult };
  });
  ipcMain.handle('get-request-logs', (_, args?: { limit?: number; offset?: number }) => {
    const limit = args?.limit ?? 20;
    const offset = args?.offset ?? 0;
    return globalMcpServer.getRequestLogs(limit, offset);
  });
  ipcMain.handle('clear-request-logs', () => {
    globalMcpServer.clearRequestLogs();
  });
  ipcMain.handle('logs:terminate-request', (_, logId: string) => {
    return globalMcpServer.terminateRequest(logId);
  });
  ipcMain.handle('logs:terminate-all-pending', () => {
    return globalMcpServer.terminateAllPendingRequests();
  });

  ipcMain.handle('get-config', () => currentConfig);
  ipcMain.handle('config:get', () => currentConfig);
  ipcMain.handle('config:update-balanced-mode', (_, balanced: boolean) => {
    currentConfig = {
      ...currentConfig,
      balancedMode: balanced,
      coding: {
        ...(currentConfig.coding || { primaryProvider: 'claude', fallbackProviders: ['chatgpt', 'gemini', 'grok'] }),
        balancedMode: balanced,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return currentConfig;
  });
  ipcMain.handle('config:update-double-agent', (_, updates: Partial<doubleAgentConfig>) => {
    const currentDoubleAgent = currentConfig.doubleAgent || {
      enabled: false,
      includeLocalLlm: false,
      modes: {
        general: true,
        coding: true,
        image: true,
        video: true,
        music: true,
      },
    };
    currentConfig = {
      ...currentConfig,
      doubleAgent: {
        ...currentDoubleAgent,
        ...updates,
        modes: updates.modes
          ? { ...(currentDoubleAgent.modes || {}), ...updates.modes }
          : currentDoubleAgent.modes,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return currentConfig.doubleAgent;
  });
  ipcMain.handle('config:toggle-double-agent', (_, enabled?: boolean) => {
    const currentVal = currentConfig.doubleAgent?.enabled ?? false;
    const nextVal = enabled !== undefined ? enabled : !currentVal;
    currentConfig = {
      ...currentConfig,
      doubleAgent: {
        ...(currentConfig.doubleAgent || { includeLocalLlm: false }),
        enabled: nextVal,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return nextVal;
  });
  ipcMain.handle('config:toggle-double-agent-mode', (_, { mode, enabled }: { mode: RouteMode; enabled?: boolean }) => {
    const existingModes = currentConfig.doubleAgent?.modes || {
      general: true,
      coding: true,
      image: true,
      video: true,
      music: true,
    };
    const currentVal = existingModes[mode] ?? true;
    const nextVal = enabled !== undefined ? enabled : !currentVal;
    currentConfig = {
      ...currentConfig,
      doubleAgent: {
        ...(currentConfig.doubleAgent || { enabled: false, includeLocalLlm: false }),
        modes: {
          ...existingModes,
          [mode]: nextVal,
        },
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return nextVal;
  });
  ipcMain.handle('config:update-recall', (_, recallCfg: Partial<RecallConfig>) => {
    const existingModes = currentConfig.recall?.modes || {
      general: true,
      coding: true,
      image: true,
      video: true,
      music: true,
    };
    currentConfig = {
      ...currentConfig,
      recall: {
        ...(currentConfig.recall || { enabled: true, strategy: 'single-pass', autoTriggerKeywords: true }),
        ...recallCfg,
        modes: recallCfg.modes
          ? { ...existingModes, ...recallCfg.modes }
          : (currentConfig.recall?.modes || existingModes),
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    return currentConfig;
  });
  ipcMain.handle('recall:toggle', (_, enabled?: boolean) => {
    const currentVal = currentConfig.recall?.enabled ?? true;
    const nextVal = enabled !== undefined ? enabled : !currentVal;
    currentConfig = {
      ...currentConfig,
      recall: {
        ...(currentConfig.recall || { strategy: 'single-pass', autoTriggerKeywords: true }),
        enabled: nextVal,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    return nextVal;
  });
  ipcMain.handle('recall:toggle-mode', (_, { mode, enabled }: { mode: RouteMode; enabled?: boolean }) => {
    const currentModes = currentConfig.recall?.modes || {
      general: true,
      coding: true,
      image: true,
      video: true,
      music: true,
    };
    const currentVal = currentModes[mode] ?? true;
    const nextVal = enabled !== undefined ? enabled : !currentVal;
    currentConfig = {
      ...currentConfig,
      recall: {
        ...(currentConfig.recall || { enabled: true, strategy: 'single-pass', autoTriggerKeywords: true }),
        modes: {
          ...currentModes,
          [mode]: nextVal,
        },
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    return nextVal;
  });
  ipcMain.handle('recall:get-status', () => currentConfig.recall || {
    enabled: true,
    strategy: 'single-pass',
    autoTriggerKeywords: true,
    modes: {
      general: true,
      coding: true,
      image: true,
      video: true,
      music: true,
    },
  });

  // Agent Halt Guard IPC Handlers
  ipcMain.handle('config:toggle-agent-guard', (_, { mode, enabled }: { mode: RouteMode; enabled?: boolean }) => {
    const currentMap = (typeof currentConfig.agentHaltGuard === 'object' && currentConfig.agentHaltGuard !== null)
      ? currentConfig.agentHaltGuard
      : { general: true, coding: true, image: true, video: true, music: true };
    const currentVal = currentMap[mode] ?? true;
    const nextVal = enabled !== undefined ? enabled : !currentVal;
    currentConfig = {
      ...currentConfig,
      agentHaltGuard: {
        ...currentMap,
        [mode]: nextVal,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return nextVal;
  });

  ipcMain.handle('config:update-agent-guard', (_, guardCfg: Partial<AgentHaltGuardConfig>) => {
    const currentMap = (typeof currentConfig.agentHaltGuard === 'object' && currentConfig.agentHaltGuard !== null)
      ? currentConfig.agentHaltGuard
      : { general: true, coding: true, image: true, video: true, music: true };
    currentConfig = {
      ...currentConfig,
      agentHaltGuard: {
        ...currentMap,
        ...guardCfg,
      },
    };
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return currentConfig.agentHaltGuard;
  });
  ipcMain.handle('update-config', (_, newCfg: Partial<TransgenticConfig>) => {
    if (newCfg.cli !== undefined) throw new Error('Use the CLI settings controls to change CLI permissions.');
    currentConfig = { ...currentConfig, ...newCfg };
    if (newCfg.assetsDir) {
      globalAssetManager.setAssetsDirectory(newCfg.assetsDir);
      globalRecipeManager.setStorageDirectory(newCfg.assetsDir);
    }
    if (newCfg.localLLM) {
      DynamicRouter.setLocalLlmConfig(currentConfig.localLLM || null);
    }
    globalHealingManager.setTransgenticConfig(currentConfig);
    globalRateLimiter.updateConfig(currentConfig);
    globalMcpServer.updateConfig(currentConfig);
    savePersistedConfig(currentConfig);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return currentConfig;
  });

  ipcMain.handle('get-route-matrix', () => DynamicRouter.getRouteMatrix());
  ipcMain.handle('get-mode-routes', () => DynamicRouter.getAllRouteConfigs());
  ipcMain.handle('update-mode-route', (_, { mode, config, pipeline }: { mode: RouteMode; config: any; pipeline?: 'main' | 'co' }) => {
    const res = DynamicRouter.updateRouteConfig(mode, config, pipeline);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('route-matrix-updated', DynamicRouter.getRouteMatrix());
    }
    return res;
  });
  ipcMain.handle('reset-mode-routes', () => {
    const res = DynamicRouter.resetRoutes();
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('route-matrix-updated', DynamicRouter.getRouteMatrix());
    }
    return res;
  });

  // Local LLM Configuration & Discovery Handlers
  ipcMain.handle('localllm:fetch-models', async (_, { baseUrl, preset }: { baseUrl: string; preset: 'ollama' | 'lmstudio' | 'custom' }) => {
    return await LocalLlmClient.fetchModels(baseUrl, preset);
  });

  ipcMain.handle('localllm:test-connection', async (_, cfg: LocalLLMConfig) => {
    return await LocalLlmClient.testConnection(cfg);
  });

  ipcMain.handle('localllm:update-config', (_, updates: Partial<LocalLLMConfig>) => {
    currentConfig = {
      ...currentConfig,
      localLLM: {
        ...(currentConfig.localLLM || {
          enabled: false,
          preset: 'ollama',
          baseUrl: 'http://127.0.0.1:11434',
          selectedModel: '',
          temperature: 0.2,
          contextLength: 8192,
          localMicroTask: false,
          localZeroLeak: false,
          localCompact: false,
          compactThresholdChars: 4000,
          attachmentKinds: [],
        }),
        ...updates,
      },
    };
    savePersistedConfig(currentConfig);
    globalMcpServer.updateConfig(currentConfig);
    globalHealingManager.setTransgenticConfig(currentConfig);
    if (currentConfig.localLLM) {
      DynamicRouter.setLocalLlmConfig(currentConfig.localLLM);
    }
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('config-updated', currentConfig);
    }
    return currentConfig.localLLM;
  });

  // DOM Watchdog & Self-Healing Engine Handlers
  ipcMain.handle('healing:audit-provider', async (_, providerId: ProviderId) => {
    return await globalHealingManager.auditProvider(providerId);
  });

  ipcMain.handle('healing:heal-provider', async (_, providerId: ProviderId) => {
    return await globalHealingManager.healProvider(providerId);
  });

  ipcMain.handle('healing:get-status', () => {
    return {
      config: globalHealingManager.getConfig(),
      reports: globalHealingManager.getAllReports(),
    };
  });

  ipcMain.handle('healing:update-config', (_, updates: Partial<HealingConfig>) => {
    currentConfig = {
      ...currentConfig,
      healing: {
        ...(currentConfig.healing || {
          autoHealingEnabled: true,
          checkIntervalMinutes: 60,
          checkOnPageLoad: true,
          checkModelSelector: true,
        }),
        ...updates,
      },
    };
    savePersistedConfig(currentConfig);
    globalMcpServer.updateConfig(currentConfig);
    const updated = globalHealingManager.updateConfig(updates);
    return updated;
  });

  globalHealingManager.onUpdate((reports) => {
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('healing-reports-updated', reports);
    }
  });

  // Custom Recipe Management IPC Handlers
  ipcMain.handle('recipes:get-all', () => {
    return globalRecipeManager.getCustomRecipes();
  });

  ipcMain.handle('recipes:install', async (_, { recipe, cookies }) => {
    const result = await globalRecipeManager.installRecipe(recipe, cookies);
    BrowserWindow.getAllWindows().forEach((win) => {
      if (!win.isDestroyed()) {
        win.webContents.send('recipe:installed', result);
        win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
        win.webContents.send('services-manifest-updated', ServiceManifestManager.getManifest());
        win.webContents.send('models-updated', ModelRegistryManager.getRegistry());
        win.webContents.send('route-matrix-updated', DynamicRouter.getRouteMatrix());
        win.webContents.send('mode-routes-updated', DynamicRouter.getAllRouteConfigs());
      }
    });
    return result;
  });

  ipcMain.handle('recipes:delete', (_, recipeId: string) => {
    const success = globalRecipeManager.deleteRecipe(recipeId);
    if (success) {
      BrowserWindow.getAllWindows().forEach((win) => {
        if (!win.isDestroyed()) {
          win.webContents.send('recipe:deleted', { id: recipeId });
          win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
          win.webContents.send('services-manifest-updated', ServiceManifestManager.getManifest());
          win.webContents.send('models-updated', ModelRegistryManager.getRegistry());
          win.webContents.send('route-matrix-updated', DynamicRouter.getRouteMatrix());
          win.webContents.send('mode-routes-updated', DynamicRouter.getAllRouteConfigs());
        }
      });
    }
    return { success };
  });

  ipcMain.handle('recipes:detect', async (_, { domSnippet, url, title }) => {
    try {
      const recipe = await globalRecipeManager.detectSelectorsWithLocalLlm(
        domSnippet,
        url,
        title,
        currentConfig.localLLM
      );
      return { success: true, recipe };
    } catch (err: any) {
      return { success: false, error: err?.message || String(err) };
    }
  });

  ipcMain.handle('recipes:get-inspector-script', () => {
    const candidates = [
      path.join(process.resourcesPath || '', 'extensions', 'transgentic-sync', 'content', 'inspectorOverlay.js'),
      path.join(app.getAppPath(), 'extensions', 'transgentic-sync', 'content', 'inspectorOverlay.js'),
      path.join(process.cwd(), 'extensions', 'transgentic-sync', 'content', 'inspectorOverlay.js'),
    ];
    for (const p of candidates) {
      if (fs.existsSync(p)) {
        return fs.readFileSync(p, 'utf-8');
      }
    }
    return null;
  });

  ipcMain.handle('recipes:reset-to-default', async (_, providerId: string) => {
    const success = globalRecipeManager.resetToDefault(providerId);
    if (success) {
      BrowserWindow.getAllWindows().forEach((win) => {
        if (!win.isDestroyed()) {
          win.webContents.send('recipe:installed', { success: true, id: providerId });
          win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
        }
      });
    }
    return { success };
  });

  ipcMain.handle('recipes:rollback', async (_, { providerId, version }: { providerId: string; version: string }) => {
    const recipe = globalRecipeManager.rollbackRecipe(providerId, version);
    if (recipe) {
      BrowserWindow.getAllWindows().forEach((win) => {
        if (!win.isDestroyed()) {
          win.webContents.send('recipe:installed', { success: true, id: providerId, recipe });
          win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
        }
      });
      return { success: true, recipe };
    }
    return { success: false, error: 'Snapshot not found' };
  });

  ipcMain.handle('recipes:get-history', (_, providerId: string) => {
    return globalRecipeManager.getRecipeHistory(providerId);
  });

  // Session Synchronization & Extension Directory IPC Handlers
  ipcMain.handle('auth:sync-session', async (_, payload) => {
    const { CookieSyncManager } = await import('./auth/cookieSyncServer.js');
    return CookieSyncManager.syncSession(payload);
  });

  ipcMain.handle('auth:open-extension-directory', async () => {
    const { shell } = await import('electron');
    const candidates = [
      path.join(process.resourcesPath || '', 'extensions', 'transgentic-sync'),
      path.join(app.getAppPath(), 'extensions', 'transgentic-sync'),
      path.join(process.cwd(), 'extensions', 'transgentic-sync'),
    ];
    for (const p of candidates) {
      if (fs.existsSync(p)) {
        await shell.openPath(p);
        return { success: true, path: p };
      }
    }
    return { success: false, error: 'Extension directory not found' };
  });

  ipcMain.handle('auth:download-extension-zip', async () => {
    const { shell, dialog } = await import('electron');
    const candidates = [
      path.join(process.resourcesPath || '', 'extensions', 'transgentic-sync.zip'),
      path.join(app.getAppPath(), 'extensions', 'transgentic-sync.zip'),
      path.join(process.cwd(), 'extensions', 'transgentic-sync.zip'),
    ];

    let foundZip: string | null = null;
    for (const p of candidates) {
      if (fs.existsSync(p)) {
        foundZip = p;
        break;
      }
    }

    if (!foundZip) {
      const downloadUrl = getExtensionDownloadUrl(app.getVersion());
      await shell.openExternal(downloadUrl);
      return { success: true, externalDownload: true, downloadUrl };
    }

    const defaultFilename = 'transgentic-sync.zip';
    const win = globalWindowManager.getMainWindow();
    const result = await dialog.showSaveDialog(win!, {
      title: 'Save Transgentic Chrome Sync Extension',
      defaultPath: path.join(app.getPath('downloads'), defaultFilename),
      filters: [{ name: 'ZIP Archive', extensions: ['zip'] }],
    });

    if (!result.canceled && result.filePath) {
      fs.copyFileSync(foundZip, result.filePath);
      shell.showItemInFolder(result.filePath);
      return { success: true, savedPath: result.filePath };
    }
    return { success: false, canceled: true };
  });

  // Model Registry & Availability Controls
  ipcMain.handle('models:get-state', () => ModelRegistryManager.getRegistry());
  ipcMain.handle('models:update-config', (_, { providerId, config }: { providerId: ProviderId; config: Partial<ProviderConfig> }) => {
    const updated = ModelRegistryManager.updateProviderConfig(providerId, config);
    if (config.hourlyLimit) {
      globalRateLimiter.setHourlyLimit(providerId, config.hourlyLimit);
    }
    return updated;
  });
  ipcMain.handle('models:toggle-model', (_, { providerId, modelId, userEnabled }: { providerId: ProviderId; modelId: string; userEnabled: boolean }) => {
    return ModelRegistryManager.toggleModel(providerId, modelId, userEnabled);
  });
  ipcMain.handle('models:toggle-service', async (_, args: any) => {
    const providerId: ProviderId = args.providerId || args.serviceId;
    const serviceEnabled: boolean = typeof args.serviceEnabled === 'boolean' ? args.serviceEnabled : args.enabled;
    if (serviceEnabled && !isCliProvider(providerId)) await globalRecipeManager.confirmEnable(providerId);
    if (!serviceEnabled && isCliProvider(providerId)) globalCliRuntime.cancelProvider(providerId);
    const reg = ModelRegistryManager.toggleService(providerId, serviceEnabled);
    const manifest = ServiceManifestManager.setServiceEnabled(providerId, serviceEnabled);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', manifest);
    }
    if (serviceEnabled && isCliProvider(providerId)) {
      void globalCliRuntime.testEnabledConnections([providerId]);
    }
    return reg;
  });
  ipcMain.handle('models:resync', async (_, targetProvider?: ProviderId) => {
    const providersToSync: ProviderId[] = targetProvider
      ? [targetProvider]
      : (ServiceManifestManager.getEnabledProviders().filter((p) => p !== 'localllm' && !isCliProvider(p) && !p.startsWith('api_')) as ProviderId[]);
    for (const p of providersToSync) {
      if (isCliProvider(p)) { await globalCliRuntime.probe(p); continue; }
      try {
        const contents = await globalSessionManager.ensureWebContents(p);
        const discovered = await ModelScraperEngine.discoverModels(p, contents);
        if (discovered && discovered.length > 0) {
          ModelRegistryManager.mergeDiscoveredModels(p, discovered);
        }
      } catch (e: any) {
        console.warn(`[Transgentic] Model resync notice for ${p}:`, e.message);
      }
    }
    return ModelRegistryManager.getRegistry();
  });

  // Native File Picker Dialog & Port Re-bind
  ipcMain.handle('settings:select-directory', async () => {
    const win = globalWindowManager.getMainWindow();
    const result = await dialog.showOpenDialog(win!, {
      properties: ['openDirectory', 'createDirectory'],
      title: 'Select Local Media & Assets Storage Directory',
    });
    if (!result.canceled && result.filePaths.length > 0) {
      const selected = result.filePaths[0];
      globalAssetManager.setAssetsDirectory(selected);
      globalRecipeManager.setStorageDirectory(selected);
      currentConfig.assetsDir = selected;
      savePersistedConfig(currentConfig);
      return selected;
    }
    return null;
  });

  ipcMain.handle('settings:apply-port', async (_, newPort: number) => {
    try {
      const actualPort = await globalMcpServer.restart(newPort);
      currentConfig.port = actualPort;
      savePersistedConfig(currentConfig);
      return { success: true, port: actualPort };
    } catch (err: any) {
      return { success: false, port: currentConfig.port, error: err.message };
    }
  });
  ipcMain.handle('settings:get-network-interfaces', () => Object.entries(os.networkInterfaces()).flatMap(([name, entries]) =>
    (entries || []).filter(entry => entry.family === 'IPv4' && !entry.internal).map(entry => ({ name, address: entry.address }))
  ));
  ipcMain.handle('settings:apply-network-access', async (_, { lanEnabled, advertisedAddress }: { lanEnabled: boolean; advertisedAddress: string }) => {
    const available = Object.values(os.networkInterfaces()).flatMap(entries => entries || []).filter(entry => entry.family === 'IPv4' && !entry.internal).map(entry => entry.address);
    if (lanEnabled && !available.includes(advertisedAddress)) return { success: false, port: currentConfig.port, error: 'Select an available local network address.' };
    currentConfig = { ...currentConfig, serverAccess: { lanEnabled: Boolean(lanEnabled), advertisedAddress: lanEnabled ? advertisedAddress : '' } };
    globalMcpServer.updateConfig(currentConfig);
    try {
      const actualPort = await globalMcpServer.restart(currentConfig.port);
      currentConfig.port = actualPort;
      savePersistedConfig(currentConfig);
      return { success: true, port: actualPort, serverAccess: currentConfig.serverAccess };
    } catch (error: any) { return { success: false, port: currentConfig.port, error: error?.message || 'Could not apply network access.' }; }
  });

  // Native Local Media Asset Inspection & System Handlers
  ipcMain.handle('media:open-file', async (_, rawPath: string) => {
    try {
      const filePath = sanitizeLocalPath(rawPath);
      if (filePath && fs.existsSync(filePath)) {
        await shell.openPath(filePath);
        return { success: true };
      }
      return { success: false, error: 'File not found on local disk' };
    } catch (e: any) {
      return { success: false, error: e?.message };
    }
  });

  ipcMain.handle('media:show-in-folder', async (_, rawPath: string) => {
    try {
      const filePath = sanitizeLocalPath(rawPath);
      if (filePath && fs.existsSync(filePath)) {
        shell.showItemInFolder(filePath);
        return { success: true };
      }
      return { success: false, error: 'File not found on local disk' };
    } catch (e: any) {
      return { success: false, error: e?.message };
    }
  });

  ipcMain.handle('media:get-file-data', async (_, rawPath: string) => {
    try {
      const filePath = sanitizeLocalPath(rawPath);
      if (filePath && fs.existsSync(filePath)) {
        const mime = getMediaMimeType(filePath);
        const buf = await fs.promises.readFile(filePath);
        const dataUrl = `data:${mime};base64,${buf.toString('base64')}`;
        return { exists: true, dataUrl, mimeType: mime, sizeBytes: buf.length };
      }
      return { exists: false, error: 'File not found on local disk' };
    } catch (e: any) {
      return { exists: false, error: e?.message };
    }
  });

  ipcMain.handle('open-provider-drawer', (_, providerId: ProviderId) => {
    globalWindowManager.setDrawerState(true);
  });

  ipcMain.handle('close-provider-drawer', () => {
    globalWindowManager.setDrawerState(false);
  });

  ipcMain.handle('set-mode', (_, mode: TaskMode | 'writing' | 'music') => {
    globalMcpServer.setMode(normalizeTaskMode(mode));
  });

  ipcMain.handle('set-compact-mode', (_, compact: boolean) => globalWindowManager.setCompactMode(compact));
  ipcMain.handle('toggle-window-pin', () => globalWindowManager.togglePin());
  ipcMain.handle('minimize-window', () => globalWindowManager.minimize());
  ipcMain.handle('hide-to-tray', () => globalWindowManager.hide());

  ipcMain.handle('reload-provider', async (_, providerId: ProviderId) => {
    await globalSessionManager.refreshProviderStatus(providerId);
  });

  ipcMain.handle('open-provider-window', async (_, providerId: ProviderId, partitionKey?: string) => {
    globalSessionManager.openProviderWindow(providerId, partitionKey);
  });

  ipcMain.handle('open-system-browser', async (_, providerId: ProviderId) => {
    await globalSessionManager.openExternalInSystemChrome(providerId);
  });

  ipcMain.handle('open-external-url', async (_, url: string) => {
    if (typeof url === 'string' && (url.startsWith('http://') || url.startsWith('https://'))) {
      await shell.openExternal(url);
    }
  });

  ipcMain.handle('quick-prompt:select-files', async (event, { mode }: { mode?: TaskMode } = {}) => {
    if (event.sender !== globalWindowManager.getMainWindow()?.webContents || event.senderFrame !== event.sender.mainFrame) {
      throw new Error('Quick Prompt attachments are available only in the main window.');
    }
    if (mode === 'music') throw new Error('Music mode does not accept file attachments.');
    const win = globalWindowManager.getMainWindow();
    const supportedExtensions = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'pdf', 'txt', 'md', 'markdown', 'csv', 'tsv', 'json', 'jsonl', 'xml', 'yaml', 'yml', 'toml', 'ini', 'log', 'js', 'jsx', 'mjs', 'cjs', 'ts', 'tsx', 'css', 'scss', 'html', 'htm', 'py', 'rb', 'php', 'java', 'kt', 'kts', 'swift', 'go', 'rs', 'c', 'h', 'cpp', 'hpp', 'cs', 'sh', 'zsh', 'fish', 'sql', 'graphql'];
    if (mode === 'video') supportedExtensions.push('mp4', 'webm', 'mov');
    const filters = [{ name: mode === 'video' ? 'Supported images, documents, and videos' : 'Supported images and documents', extensions: supportedExtensions }];
    const result = await dialog.showOpenDialog(win!, {
      properties: ['openFile', 'multiSelections'],
      title: 'Attach files to Quick Prompt',
      filters,
    });
    if (result.canceled) return [];
    if (result.filePaths.length > ATTACHMENT_LIMITS.maxFiles) {
      throw new Error(`Select at most ${ATTACHMENT_LIMITS.maxFiles} files.`);
    }
    const selections: DesktopAttachmentSelection[] = [];
    let totalBytes = 0;
    for (const selectedPath of result.filePaths) {
      const realPath = await fs.promises.realpath(selectedPath);
      const stat = await fs.promises.stat(realPath);
      if (!stat.isFile()) throw new Error('Each attachment must be a readable regular file.');
      await fs.promises.access(realPath, fs.constants.R_OK);
      if (stat.size > ATTACHMENT_LIMITS.maxFileBytes) throw new Error(`Attachment "${path.basename(selectedPath)}" exceeds the 50 MB limit.`);
      totalBytes += stat.size;
      if (totalBytes > ATTACHMENT_LIMITS.maxTotalBytes) throw new Error('Selected attachments exceed the 100 MB total limit.');
      selections.push({ path: selectedPath, name: path.basename(selectedPath), size: stat.size });
    }
    return selections;
  });

  ipcMain.handle('execute-prompt', async (event, { prompt, mode, provider, model, cliRequest, files }: { prompt: string; mode?: TaskMode; provider?: ProviderId; model?: string; cliRequest?: unknown; files?: AttachmentInput[] }) => {
    if (event.sender !== globalWindowManager.getMainWindow()?.webContents || event.senderFrame !== event.sender.mainFrame) throw new Error('Desktop prompts are available only in the main window.');
    const result = await globalMcpServer.orchestratePrompt(
      prompt,
      mode || 'general',
      provider,
      undefined,
      model,
      undefined,
      'quick_prompt_session',
      false,
      true,
      undefined,
      { profile: 'plain', sessionId: `desktop_${event.sender.id}`, cliRequest: cliRequest as any, isLoopback: true },
      files
    );
    if (result.isError) throw new Error(result.content?.[0]?.text || 'Request failed');
    return result;
  });

  // Active Thread & Session Clear Handlers
  ipcMain.handle('threads:get-sessions', () => {
    return globalThreadManager.getAllSessions();
  });

  ipcMain.handle('threads:clear-sessions', async (event, { providerId, threadId, scope }: { providerId?: ProviderId; threadId?: string; scope?: 'quick_prompt' | 'all' } = {}) => {
    if (scope === 'quick_prompt') {
      for (const session of globalThreadManager.getAllSessions()) {
        if (isQuickPromptConversation(session.threadId, `desktop_${event.sender.id}`)
          && (!providerId || session.provider === providerId)
          && (!threadId || session.threadId === threadId)) {
          globalThreadManager.removeSession(session.threadId, session.provider);
        }
      }
      // Navigate on the next Quick Prompt inside the account queue, not while an
      // unrelated MCP request may be using the same provider's browser view.
      return { success: true, sessions: globalThreadManager.getAllSessions() };
    }
    if (providerId && threadId) {
      globalThreadManager.removeSession(threadId, providerId);
    } else if (providerId) {
      for (const sess of globalThreadManager.getAllSessions()) {
        if (sess.provider === providerId) {
          globalThreadManager.removeSession(sess.threadId, sess.provider);
        }
      }
    } else {
      globalThreadManager.clearAll();
    }

    // Direct active provider adapters to navigate to a new chat
    const adapters = globalSessionManager.getAdapters();
    for (const adapter of adapters) {
      if (!providerId || adapter.providerId === providerId) {
        try {
          await adapter.navigateToNewChat();
        } catch {}
      }
    }

    return { success: true, sessions: globalThreadManager.getAllSessions() };
  });

  // Developer-Level AI Services Manifest & Conflict Handlers
  ipcMain.handle('services:get-manifest', () => {
    return ServiceManifestManager.getManifest();
  });

  ipcMain.handle('services:toggle-experimental', async (_, { serviceId, enabled }: { serviceId: ProviderId; enabled: boolean }) => {
    if (enabled) await globalRecipeManager.confirmEnable(serviceId);
    const updated = ServiceManifestManager.setServiceEnabled(serviceId, enabled);
    ModelRegistryManager.toggleService(serviceId, enabled);
    await globalSessionManager.refreshProviderStatus(serviceId);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
      win.webContents.send('models-updated', ModelRegistryManager.getRegistry());
      win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
    }
    return updated;
  });

  ipcMain.handle('services:update-manifest', async (_, { serviceId, updates }: { serviceId: ProviderId; updates: any }) => {
    if (updates?.enabled === true) await globalRecipeManager.confirmEnable(serviceId);
    const updated = ServiceManifestManager.updateServiceEntry(serviceId, updates);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
    }
    return updated;
  });

  ipcMain.handle('services:get-conflicts', () => {
    return ServiceManifestManager.checkRouteConflicts(DynamicRouter.getAllRouteConfigs());
  });

  ipcMain.handle('services:add-api-provider', (_, entry: { name: string; baseUrl: string; apiKey?: string; defaultModelId?: string; attachmentKinds?: import('../shared/attachments.js').AttachmentKind[] }) => {
    const updated = ServiceManifestManager.addCustomApiProvider(entry);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
    }
    return updated;
  });

  ipcMain.handle('services:update-api-provider', (_, { serviceId, entry }: { serviceId: ProviderId; entry: any }) => {
    const updated = ServiceManifestManager.updateCustomApiProvider(serviceId, entry);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
    }
    return updated;
  });

  ipcMain.handle('services:delete-provider', async (_, serviceId: ProviderId) => {
    // 1. Unregister and clear from session manager
    try {
      globalSessionManager.unregisterAdapter(serviceId);
    } catch {}

    // 2. Remove provider from Model Registry
    try {
      ModelRegistryManager.deleteProviderConfig(serviceId);
    } catch {}

    // 3. Remove from Recipe Manager if installed
    try {
      globalRecipeManager.deleteRecipe(serviceId);
    } catch {}

    // 4. Remove provider from all dynamic routes
    try {
      DynamicRouter.removeProviderFromAllRoutes(serviceId);
    } catch {}

    // 5. Delete from Service Manifest
    const updated = ServiceManifestManager.deleteProvider(serviceId);

    // 6. Broadcast all updates to windows
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
      win.webContents.send('provider-status-updated', globalSessionManager.getAllStatuses());
      win.webContents.send('models-updated', ModelRegistryManager.getRegistry());
      win.webContents.send('route-matrix-updated', DynamicRouter.getRouteMatrix());
      win.webContents.send('mode-routes-updated', DynamicRouter.getAllRouteConfigs());
    }
    return updated;
  });

  ipcMain.handle('services:update-title', (_, { serviceId, title }: { serviceId: ProviderId; title: string }) => {
    const updated = ServiceManifestManager.updateServiceTitle(serviceId, title);
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('services-manifest-updated', updated);
    }
    return updated;
  });

  // Multi-Account Profile Registry Handlers
  ipcMain.handle('accounts:get-all', () => {
    return AccountRegistryManager.getAll();
  });

  ipcMain.handle('accounts:get-for-provider', (_, providerId: ProviderId) => {
    return AccountRegistryManager.getForProvider(providerId);
  });

  ipcMain.handle('accounts:add', (_, { providerId, alias }: { providerId: ProviderId; alias: string }) => {
    const newAccount = AccountRegistryManager.addAccount(providerId, alias);
    globalSessionManager.configureSession(newAccount.partitionKey);
    return newAccount;
  });

  ipcMain.handle('accounts:update-alias', (_, { providerId, accountId, alias }: { providerId: ProviderId; accountId: string; alias: string }) => {
    return AccountRegistryManager.updateAlias(providerId, accountId, alias);
  });

  ipcMain.handle('accounts:set-main', (_, { providerId, accountId }: { providerId: ProviderId; accountId: string }) => {
    return AccountRegistryManager.setMainAccount(providerId, accountId);
  });

  ipcMain.handle('accounts:set-active', async (_, { providerId, accountId }: { providerId: ProviderId; accountId: string }) => {
    const updated = AccountRegistryManager.setActiveAccount(providerId, accountId);
    const active = updated.accounts.find((a) => a.id === accountId);
    if (active) {
      globalSessionManager.configureSession(active.partitionKey);
      const adapter = globalSessionManager.getAdapter(providerId);
      if (adapter) {
        adapter.setCustomPartition(active.partitionKey);
      }
      await globalSessionManager.refreshProviderStatus(providerId);
    }
    return updated;
  });

  ipcMain.handle('accounts:reorder', (_, { providerId, accountIds }: { providerId: ProviderId; accountIds: string[] }) => {
    return AccountRegistryManager.reorderAccounts(providerId, accountIds);
  });

  ipcMain.handle('accounts:delete', (_, { providerId, accountId }: { providerId: ProviderId; accountId: string }) => {
    return AccountRegistryManager.deleteAccount(providerId, accountId);
  });

  // MCP Client Authentication Handlers
  ipcMain.handle('auth:get-token', () => {
    return ClientAuthManager.getMasterToken();
  });

  ipcMain.handle('auth:regenerate-token', () => {
    const newToken = ClientAuthManager.regenerateToken();
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('auth-token-updated', newToken);
    }
    return newToken;
  });

  ipcMain.handle('auth:verify-token', (_, token: string) => {
    return ClientAuthManager.verifyToken(token);
  });

  ClientAuthManager.onTokenUpdated((token) => {
    const win = globalWindowManager.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('auth-token-updated', token);
    }
  });
}

app.on('before-quit', () => {
  globalWindowManager.isQuitting = true;
  globalCliRuntime.dispose();
  globalMcpServer.stop();
  trayManager?.destroy();
});

app.on('window-all-closed', () => {
  // Keep alive in tray on macOS & Windows
});

bootstrap();
